# Generated by Django 4.1.7 on 2023-03-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
