# Generated by Django 4.1.7 on 2023-03-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_subject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='level',
        ),
    ]
