# Generated by Django 4.1.7 on 2023-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_student_parent_email_remove_teacher_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
