# Generated by Django 4.1.7 on 2023-03-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursematerial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='course/audio'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='summary_audio',
            field=models.FileField(blank=True, null=True, upload_to='course/audio/summaries/'),
        ),
    ]
