# Generated by Django 4.1.7 on 2023-03-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursematerial_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='course/static/audio'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='summary_audio',
            field=models.FileField(blank=True, null=True, upload_to='course/static/summaries/'),
        ),
    ]
